Add a retry on failed oc cluster up to travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,7 +53,25 @@ before_install:
       echo $PATH
       # below cmd is important to get oc working in ubuntu
       sudo docker run -v /:/rootfs -ti --rm --entrypoint=/bin/bash --privileged openshift/origin:v1.5.1 -c "mv /rootfs/bin/findmnt /rootfs/bin/findmnt.backup"
-      sudo oc cluster up --host-config-dir=/home/travis/gopath/src/github.com/radanalyticsio/origin
+
+      # Sometimes oc cluster up fails with a permission error and works when the test is relaunched.
+      # See if a retry within the same test works
+      set +e
+      built=false
+      for tries in {1..3}; do
+          sudo oc cluster up --host-config-dir=/home/travis/gopath/src/github.com/radanalyticsio/origin
+          if [ "$?" -eq 0 ]; then
+              built=true
+              break
+          fi
+          echo "Retrying oc cluster up after failure"
+          sudo oc cluster down
+      done
+      set -e
+      if [ "$built" == false ]; then
+          exit 1
+      fi
+
       sudo chmod -R a+rwX /home/travis/.kube
       sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/origin
       # find IP:PORT of openshift
