This change adds tests for templates maintained in the oshinko-s2i reposoitory as well as https://radanalytics.io/resources.yaml.
These tests are focused on ensuring that the templates are able
to correctly:

* set environment variables expected by the s2i build process
* set environment variables expected by the start.sh script
  in the running application image
* configure downward api elements expected by start.sh

They are not concerned with the actual operation of start.sh
beyond checking that the application pod actually starts
(start.sh functionality is covered elsewhere). In essence, they
are checks of the "API" for our s2i scripts and start.sh.

diff --git a/test/e2e/common b/test/e2e/common
--- a/test/e2e/common
+++ b/test/e2e/common
@@ -154,9 +154,15 @@ function run_job() {
 
 function cleanup_app() {
 
-    oc scale dc/"$APP_NAME" --replicas=0 > /dev/null
+    # We may have code shared by build templates and app templates
+    # that calls cleanup_app, and the build tempaltes may not have dcs ...
+    set +e
+    oc scale dc/"$APP_NAME" --replicas=0 &> /dev/null
+    set -e
     os::cmd::try_until_text 'oc get pods -l deploymentconfig="$APP_NAME"' 'No resources found' > /dev/null
-    oc delete dc/"$APP_NAME" > /dev/null
+    set +e
+    oc delete dc/"$APP_NAME" &> /dev/null
+    set -e
     if [ "$#" -eq 1 ]; then
         os::cmd::try_until_failure 'oc get dc "$MASTER_DC"' > /dev/null
         os::cmd::try_until_failure 'oc get dc "$WORKER_DC"' > /dev/null
@@ -182,6 +188,7 @@ function cleanup_cluster() {
 } 
 
 function make_image() {
+    TEST_IMAGE=play
     set +e
     oc get buildconfig play &> /dev/null
     res=$?
